spring.application.name=ev-roadtrip-optimizer
spring.datasource.url=jdbc:postgresql://localhost:5432/ev_road_trip_optimizer
spring.datasource.username=postgres
spring.datasource.password=Shuaib@7
spring.jpa.hibernate.ddl-auto=update